site_name: RadioKociaMuzyka - dokumentacja

docs_dir: .

nav:
  - 'index.md'
  - 'about.md'

theme: 
  name: readthedocs
  color_mode: dark
  logo: https://avatars.githubusercontent.com/u/207432944?s=64&v=4